### ISSUE TITLE
Support asynchronous IO

### ISSUE THREAD

**Issue by chucker** [m6t/M6T.Core.TupleModelBinder#1]
As of ASP.NET Core 3.0, [synchronous IO is no longer allowed by default](https://github.com/aspnet/AspNetCore/issues/7644). The framework will throw 500.

As such, the readme should be amended with something like:

```csharp
services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

In the long run, this should be fixed in the library. My guess is `var body = reader.ReadToEnd();` is the offending call.

**Comment by m6t** [comment]
fixed by making IO asynchronous with #2
