### ISSUE TITLE
Does not work with Guid?

### ISSUE THREAD

**Issue by bar10dr** [m6t/M6T.Core.TupleModelBinder#5]
Error
Newtonsoft.Json.JsonReaderException: Input string '728cb7a1-b8eb-471e-a90d-f17531baf918' is not a valid number. Path '', line 1, position 36.

`{"clientId":"728cb7a1-b8eb-471e-a90d-f17531baf918","name":"Name1","email":"email@email.com"}`

```
public ActionResult<string> AddItem((Guid clientId, string name, string email) Item)
{
}

```

**Comment by m6t** [comment]
Thanks for the input.
This is now fixed in https://github.com/m6t/M6T.Core.TupleModelBinder/commit/020ce4b46ffaedc2858ec0592206cb7b82d52477 and the change is included in 1.2.1 version on nuget
